### ISSUE TITLE
Update Yet Another Hue API to version 2.5.0

### ISSUE THREAD

**Issue by ZeroOne3010** [philipparndt/mqtt-to-telegram#11]
Hi there! Philips has announced that they are deprecating HTTP support in favor of HTTPS in their Hue bridges. When exactly will this happen is anyone's guess, but the fact is that eventually, after some random bridge firmware update, HTTP connections will just stop working.

I'm letting you know because you are using (a fork of) Yet Another Hue API library that I've written. The old versions of the library are using HTTP connections by default, which puts your app too at risk of just ceasing to work. If you would update to version **2.5.0**, however, it would use HTTPS by default. You could also just use the `new Hue(HueBridgeProtocol.UNVERIFIED_HTTPS, bridgeIp, apiKey)` constructor with that `UNVERIFIED_HTTPS` argument, but unfortunately if you are using bridge discovery, then that still would not work but would need the newer version of the library.

Sorry for the trouble, but as always, let me know if you have any issues or improvement suggestions with the library! Cheers! 😃

**Comment by ZeroOne3010** [comment]
Also, this would apparently also apply to this other project of yours: https://github.com/philipparndt/hue-to-mqtt-gw

**Comment by philipparndt** [comment]
Hi @ZeroOne3010 
this post really made my day. Thank you a lot for letting me know 😄
